# Generated by Django 5.0.1 on 2024-01-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_dishes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
